name: Carpentry Push
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: arcaflow-plugin-wait
  IMAGE_TAG: 'latest'
  QUAY_NAMESPACE: ${{ secrets.QUAY_NAMESPACE }}
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
jobs:
  carpenter-push:
    name: carpenter_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this project
        uses: actions/checkout@v3
      - name: carpenter build
        uses: arcalot/arcaflow-plugin-image-builder@main
        with:
          args: build --build --push
